name: Bug Report
description: Create a report to help us improve
labels: [ "bug" ]
projects: [ "ricadoboss/2" ]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Whenever I use ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: It should have ...
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step. If not applicable, delete this section."
      value: |
        1.
        2.
        3.
        ...
  - type: textarea
    attributes:
      label: Source Code
      description: The source code you used to reproduce the bug. If not applicable, delete this section.
      value: |
        // Your code here
      render: step
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: textarea
    attributes:
      label: `step --info` Output
      description: Run `step --info` in your terminal paste the output here.
      placeholder: |
        STEP - Simple Transition to Elevated Programming
        Build Date:
        Version:
        Branch:
        CLR Version:
        OS Version:
  - type: checkboxes
    attributes:
      label: "Please make sure you did the following before submitting your bug report:"
      options:
        - label: I have searched the issues to make sure this is not a duplicate
          required: true
        - label: I have included steps to reproduce the bug above
