# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths-ignore: [ "StepLang.Wiki/**" ]
    branches: [ "main" ]
  pull_request:
    paths-ignore: [ "StepLang.Wiki/**" ]
    branches: [ "main" ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [6.x, 7.x, 8.x]

    runs-on: ${{ matrix.os }}

    name: Build & Test on .NET ${{ matrix.version }} (${{ matrix.os }})

    steps:
    - name: Set git to use LF
      if: matrix.os == 'windows-latest'
      run: |
        git config --global core.autocrlf false
        git config --global core.eol lf

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.version }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

    - name: Check Style
      if: always()
      run: dotnet tool update dotnet-format -g && dotnet format --verify-no-changes
