# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths-ignore: [ "StepLang.Wiki/**" ]
    branches: [ "main" ]
  pull_request:
    paths-ignore: [ "StepLang.Wiki/**" ]
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        version: [6.x, 7.x, 8.x]
        command: ['build --configuration Release', 'test --configuration Release', 'format --verify-no-changes' ]

    runs-on: ${{ matrix.os }}

    name: Build & Test on .NET ${{ matrix.version }} (${{ matrix.os }})

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.version }}

    - name: Run dotnet ${{ matrix.command }}
      run: dotnet ${{ matrix.command }}
