name: Generate Homepage

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/homepage.yml'
      - 'StepLang.Homepage/**'

jobs:
  publish-docs:
    name: Publish Homepage

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --unshallow

      - name: Dotnet Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Build STEP
        run: dotnet build StepLang/StepLang.csproj -c Release

      - name: Generate Homepage
        run: docfx StepLang.Homepage/docfx.json

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: StepLang.Homepage/_site
