name: Publish

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
    paths:
      - ".github/workflows/publish.yml"
      - "StepLang.CLI/publish.sh"
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/publish.yml"
      - "StepLang.CLI/publish.sh"

jobs:
  build:
    name: Build Binaries

    runs-on: ubuntu-latest

    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore --locked-mode --nologo

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Publish Binaries
        run: pushd StepLang.CLI && ./publish.sh && popd

      - name: Upload Artifacts (step-linux-x64)
        uses: actions/upload-artifact@v3
        with:
          name: step-linux-x64
          path: StepLang.CLI/publish/step-linux-x64

      - name: Upload Artifacts (step-linux-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: step-linux-arm64
          path: StepLang.CLI/publish/step-linux-arm64

      - name: Upload Artifacts (step-win-x64)
        uses: actions/upload-artifact@v3
        with:
          name: step-windows-x64
          path: StepLang.CLI/publish/step-win-x64.exe

      - name: Upload Artifacts (step-win-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: step-windows-arm64
          path: StepLang.CLI/publish/step-win-arm64.exe

      - name: Upload Artifacts (step-osx-x64)
        uses: actions/upload-artifact@v3
        with:
          name: step-osx-x64
          path: StepLang.CLI/publish/step-osx-x64

      - name: Upload Artifacts (step-osx-arm64)
        uses: actions/upload-artifact@v3
        with:
          name: step-osx-arm64
          path: StepLang.CLI/publish/step-osx-arm64

      - name: Upload Artifacts (step)
        uses: actions/upload-artifact@v3
        with:
          name: step
          path: StepLang.CLI/publish/step.zip

  sign-macos:
    name: Sign macOS binary

    needs:
      - build

    runs-on: macos-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: step-osx-arm64
          path: ./artifact

      - name: Sign binary
        id: sign
        uses: lando/code-sign-action@v2
        with:
          file: ./artifact/step-osx-arm64
          certificate-data: ${{ secrets.APPLE_CERT_DATA }}
          certificate-password: ${{ secrets.APPLE_CERT_PASSWORD }}
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}

      - name: Upload Artifacts (step-osx-arm64-signed)
        uses: actions/upload-artifact@v3
        with:
          name: step-osx-arm64-signed
          path: ./artifact/step-osx-arm64

  release:
    name: Create GitHub Release

    if: startsWith(github.ref, 'refs/tags/')

    needs:
      - build
      - sign-macos

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Download binaries (step)
        uses: actions/download-artifact@v2
        with:
          name: step
          path: ./artifacts

      - name: Download binaries (step-linux-x64)
        uses: actions/download-artifact@v2
        with:
          name: step-linux-x64
          path: ./artifacts

      - name: Download binaries (step-linux-arm64)
        uses: actions/download-artifact@v2
        with:
          name: step-linux-arm64
          path: ./artifacts

      - name: Download binaries (step-win-x64)
        uses: actions/download-artifact@v2
        with:
          name: step-windows-x64
          path: ./artifacts

      - name: Download binaries (step-win-arm64)
        uses: actions/download-artifact@v2
        with:
          name: step-windows-arm64
          path: ./artifacts

      - name: Download binaries (step-osx-x64)
        uses: actions/download-artifact@v2
        with:
          name: step-osx-x64
          path: ./artifacts

      - name: Download binaries (step-osx-arm64-signed)
        uses: actions/download-artifact@v2
        with:
          name: step-osx-arm64-signed
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            These release notes are generated automatically. For more information, please refer to the [CHANGELOG.md](https://github.com/ricardoboss/STEP/blob/main/CHANGELOG.md).
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
          files: |
            StepLang.CLI/publish/*
