name: Publish

on:
  push:
    tags:
      - "v*.*.*"
    paths:
      - ".github/workflows/publish.yml"
      - "StepLang.CLI/publish.sh"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    name: Build & Publish

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Publish
        run: pushd StepLang.CLI && ./publish.sh && popd

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: |
            These release notes are generated automatically. For more information, please refer to the [CHANGELOG.md](https://github.com/ricardoboss/STEP/blob/main/CHANGELOG.md).
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            StepLang.CLI/publish/*
