name: Report

on:
  pull_request:
    paths-ignore:
      - "StepLang.Wiki/**"
      - "StepLang.Homepage/**"
    branches: [ "main" ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  coverage:
    name: Get Test Coverage

    runs-on: ubuntu-latest

    outputs:
      badge: ${{ steps.coverage.outputs.badge }}
      line_rate: ${{ steps.coverage.outputs.line_rate }}
      branch_rate: ${{ steps.coverage.outputs.branch_rate }}
      complexity: ${{ steps.coverage.outputs.complexity }}
      health: ${{ steps.coverage.outputs.health }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.x

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Provide Code Coverage Summary
        id: coverage
        uses: ricardoboss/CodeCoverageSummary@dev
        with:
          filename: coverage/**/coverage.cobertura.xml
          output: github
          fail_below_min: true
          thresholds: '0 85'
          badge: true

  style:
    name: Check Style

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Style
        id: style
        run: dotnet tool update dotnet-format -g && dotnet format --verify-no-changes

  docblocks:
    name: Check Docblocks

    runs-on: ubuntu-latest

    outputs:
      total: ${{ steps.docblocks.outputs.total }}
      undocumented: ${{ steps.docblocks.outputs.undocumented }}
      documented: ${{ steps.docblocks.outputs.documented }}
      percent: ${{ steps.docblocks.outputs.percent }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check Docblock Coverage
        id: docblocks
        run: dotnet tool update cranky -g && cranky --project ./StepLang/StepLang.csproj --github --set-exit-code --percentages 0,50

  report:
    name: Report

    if: always()
    needs: [ coverage, style, docblocks ]

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Add PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: report
          message: |
            ## Report

            ![Code Coverage](${{ needs.coverage.outputs.badge }})

            Static Analysis:

            - Code Style: ${{ needs.style.result == 'success' && '✅ OK' || '❌ Failed' }}
            - Docblocks: `${{ needs.docblocks.outputs.documented }} / ${{ needs.docblocks.outputs.total }}` (`${{ needs.docblocks.outputs.percent }}%`)
