name: Report

on:
  pull_request:
    paths-ignore:
      - "StepLang.Wiki/**"
      - "StepLang.Homepage/**"
    types: [ assigned, opened, synchronize, reopened, labeled, unlabeled ]
    branches:
      - main
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  coverage:
    name: Coverage

    runs-on: ubuntu-latest

    outputs:
      badge: ${{ steps.coverage.outputs.badge || steps.coverage-failure.outputs.badge }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.x

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Test --no-restore

      - name: Test
        run: dotnet test --configuration Test --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Post coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          format: cobertura
          files: coverage/**/coverage.cobertura.xml

  style:
    name: Check Style

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.x

      - name: Check Style
        id: style
        run: dotnet format --verify-no-changes

  changelog:
    name: Check CHANGELOG was updated

    runs-on: ubuntu-latest

    outputs:
      badge: ${{ steps.changelog.outputs.badge || steps.changelog-failure.outputs.badge }}

    steps:
      - uses: tarides/changelog-check-action@v2
        with:
          changelog: CHANGELOG.md

      - name: Provide success badge
        id: changelog
        run: |
          echo "badge=https://img.shields.io/badge/CHANGELOG-ok-brightgreen.svg?style=flat" >> "$GITHUB_OUTPUT"

      - name: Provide failure badge
        id: changelog-failure
        if: failure()
        run: |
          echo "badge=https://img.shields.io/badge/CHANGELOG-not%20updated-red.svg?style=flat" >> "$GITHUB_OUTPUT"

  report:
    name: Report

    if: always()
    needs: [ style, changelog ]

    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Add PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: report
          message: |
            ![Code Style](https://img.shields.io/badge/Code%20Style-${{ needs.style.result == 'success' && 'ok' || 'run%20`dotnet%20format`' }}-${{ needs.style.result == 'success' && 'brightgreen' || 'red' }}.svg?style=flat) \
            ![CHANGELOG](${{ needs.changelog.outputs.badge }})
