name: Synchronize Wiki

on:
  push:
    paths:
      - StepLang.Wiki/**
      - .github/workflows/wiki.yml
    branches:
      - main
      - issues/20-wiki-to-docs

jobs:
  sync:
    name: Synchronize Wiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull GitHub Wiki
        run: git clone https://github.com/$GITHUB_REPOSITORY.wiki.git _wiki
      - name: Update Wiki files
        run: |
          rsync -av --delete StepLang.Wiki/ _wiki/ --exclude .git --exclude StepLang.Wiki.csproj
      - name: Push Docs to GitHub Wiki
        run: |
          cd _wiki
          git add .
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git commit -m "${{ github.event.head_commit.message }} (${{ github.sha }})"
          git push -f --set-upstream https://github.com/$GITHUB_REPOSITORY.wiki.git master
